site_name: Sudofy Tech Session (STS)
pages:
    - Home: index.md
    - 0. Introduction: sts-intro.md
theme:
  name: 'material'
markdown_extensions:
  - footnotes
  - admonition
  - toc:
      permalink: true
